CREATE TABLE  "PERSONAL_INFO" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"IDENTIFY_CODE" NUMBER(10,0) NOT NULL ENABLE, 
	"FNAME" VARCHAR2(50), 
	"LNAME" VARCHAR2(50), 
	"NICKNAME" VARCHAR2(50), 
	"BIRTH_DATE" DATE, 
	"BIRTH_LOC" VARCHAR2(50), 
	"SERIAL_NUMBER" NUMBER(10,0), 
	"DYN" VARCHAR2(50), 
	"MAZHAB" VARCHAR2(50), 
	"TABYAT" VARCHAR2(50), 
	 CONSTRAINT "MOSHAKHSATFARDY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
/

CREATE OR REPLACE EDITIONABLE TRIGGER  "BI_MOSHAKHSATFARDY" 
  before insert on "PERSONAL_INFO"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "MOSHAKHSATFARDY_SEQ".nextval into :NEW."ID" from sys.dual; 
  end if; 
end; 

/
ALTER TRIGGER  "BI_MOSHAKHSATFARDY" ENABLE
/